CREATE TABLE `sys_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `uuid` varchar(125) NOT NULL COMMENT '唯一UUID',
  `nickname` varchar(100) DEFAULT NULL COMMENT '用户名（真实姓名）',
  `mobile` varchar(20) DEFAULT NULL COMMENT '手机号',
  `account` varchar(100) NOT NULL COMMENT '账户',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `password` varchar(500) NOT NULL COMMENT '登录密码',
  `salt` varchar(100) NOT NULL COMMENT '加密字段',
  `company_uuid` varchar(125) DEFAULT NULL COMMENT '企业信息id',
  `account_type` int(11) DEFAULT '1' COMMENT '账号类型（预留） 1：主（超级账号） 2：副（可能下级员工）',
  `user_pt` int(11) DEFAULT '1' COMMENT '用户平台 1.运营平台  2.商户平台',
  `head_url` varchar(150) DEFAULT NULL COMMENT '用户头像 uuid',
  `super_uuid` varchar(125) DEFAULT NULL COMMENT '主账号',
    `sex` int(2) DEFAULT '1' COMMENT '性别 1.男 2.女',
    `is_auth` int(2) DEFAULT '1' COMMENT '是否认证 1.未认证 2.已认证已认证情况下不允许修改',
    `card_number` varchar(20) DEFAULT NULL COMMENT '身份证号',
     `role_uuid` varchar(20) DEFAULT NULL COMMENT '所属角色',
  `version` bigint(20) DEFAULT NULL COMMENT '更新的时候版本控制',
  `create_uuid` varchar(125) DEFAULT NULL COMMENT '创建者UUID',
  `update_uuid` varchar(125) DEFAULT NULL COMMENT '更新者UUID',
  `disable_uuid` varchar(125) DEFAULT NULL COMMENT '禁用者UUID',
  `del_uuid` varchar(125) DEFAULT NULL COMMENT '删除者UUID',
  `create_at` bigint(20) DEFAULT NULL COMMENT '创建时间',
  `update_at` bigint(20) DEFAULT NULL COMMENT '更新时间',
  `disable_at` bigint(20) DEFAULT NULL COMMENT '禁用时间',
  `del_at` bigint(20) DEFAULT NULL COMMENT '删除时间',
  `sql_status` int(11) DEFAULT '1' COMMENT '数据状态 0. 删除， 1. 正常, 2. 禁用',
  `state` int(11) DEFAULT '1' COMMENT '业务状态,由务业务表根据情况定义, 1. 新建',
  `channel_id` varchar(125) DEFAULT NULL COMMENT '应用ID,数据库所有数据需要属于一个应用,channel_id就是应用ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COMMENT='用户';